### ISSUE TITLE
Roadmap 🏎️

### ISSUE THREAD

**Issue by Albert221** [Albert221/LekBierz#1]
#### Medicines list and dose history features

- [x] Adding medicines to the list
    - [x] Communication with [medicinal-products-registry-api](https://github.com/Albert221/medicinal-products-registry-api)
    - [x] Refactor adding to state so the code is more SOLID
    - [x] Refactor the structure to use Redux with built_value
- [x] Dose history with side effects
- [x] Adding dose to history
- [x] Archive screens
- [x] Prevent from actions on archived meds

#### Reminders

- [x] Way for user to provide data when to take meds
- [ ] Notifications about taking medicine
- [ ] Grouping medicines in home screen by *when to take*

#### Firebase

- [x] Integration with Firebase, data should be stored somewhere

#### Opportunities

- [ ] Basic information about active substances/medicines
- [ ] Actions to buy more meds
- [ ] Sharing side effects info for 3rd parties

## Extra stuff

- [ ] Landing page for application
- [ ] Dashboard with side effects information
- [ ] Website encouraging to using public data with live examples on [publicdata.rocks](https://publicdata.rocks).

**Comment by Albert221** [comment]
Closing in exchange for issues on specific topics.
